:construction_worker: 添加ruff

diff --git a/.github/workflows/typecheck.yml b/.github/workflows/typecheck.yml
--- a/.github/workflows/typecheck.yml
+++ b/.github/workflows/typecheck.yml
@@ -1,27 +1,55 @@
 name: Type Check
 
 on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+    push:
+        branches:
+            - main
+            - test
+    pull_request:
+        branches:
+            - main
+            - test
 
 jobs:
-  typecheck:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v3
+    typecheck:
+        runs-on: ubuntu-latest
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '16'
+        strategy:
+        matrix:
+            python-version: ["3.13"]
 
-      - name: Install pyright
-        run: npm install -g pyright
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
 
-      - name: Run pyright
-        run: pyright
+            - name: Setup Python ${{ matrix.python-version }}
+              uses: actions/setup-python@v5
+              with:
+                python-version: ${{ matrix.python-version }}
+
+            - name: Install uv
+              uses: astral-sh/setup-uv@v6.0.0
+              with:
+                version: latest
+                enable-cache: true
+                cache-dependency-glob: |
+                        uv.lock
+                        requirements.txt
+
+            - name: Install dependencies
+              run: |
+                if [ -f pyproject.toml ]; then
+                    uv sync --extras lint
+                else
+                    echo "pyproject.toml not found."
+                    exit 1
+                fi
+
+            - name: Run ruff check
+              run: |
+                uv run ruff check . --output-format=github
+              continue-on-error: true
+
+            - name: Run pyright
+              run: |
+                uv run pyright
diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -1,50 +1,50 @@
-name: Run Unit Tests
+name: Unit Tests
 
 on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+    push:
+        branches:
+            - main
+            - test
+    pull_request:
+        branches:
+            - main
+            - test
 
 jobs:
-  unittest:
-    runs-on: ubuntu-latest
+    unittest:
+        runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
+        strategy:
+        matrix:
+            python-version: ["3.13"]
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
 
-      - name: Setup Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
+            - name: Setup Python ${{ matrix.python-version }}
+              uses: actions/setup-python@v5
+              with:
+                python-version: ${{ matrix.python-version }}
 
-      - name: Install uv
-        uses: astral-sh/setup-uv@v1
-        with:
-          version: latest
-          enable-cache: true
-          cache-dependency-glob: |
-            uv.lock
-            requirements.txt
+            - name: Install uv
+              uses: astral-sh/setup-uv@v6.0.0
+              with:
+                version: latest
+                enable-cache: true
+                cache-dependency-glob: |
+                        uv.lock
+                        requirements.txt
 
-      - name: Install dependencies
-        run: |
-          if [ -f pyproject.toml ]; then
-            uv sync --with test
-          elif [ -f requirements.txt ]; then
-            uv pip install -r requirements.txt
-          else
-            echo "Neither pyproject.toml nor requirements.txt found."
-            exit 1
-          fi
+            - name: Install dependencies
+              run: |
+                if [ -f pyproject.toml ]; then
+                    uv sync --extras test
+                else
+                    echo "pyproject.toml not found."
+                    exit 1
+                fi
 
-      - name: Run unit tests
-        run: |
-          python -m unittest discover -s tests
+            - name: Run unit tests
+              run: |
+                python -m unittest discover -s tests
